### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [npm/unique-slug#2]
Would you please create a LICENSE or LICENSE.md file with your copyright information and the text of the ISC license?  The ISC license requires that the text of the license accompany the source code.  It also makes it easier for people like me who package up modules for Linux distributions.

**Comment by radiovisual** [comment]
>  It also makes it easier for people like me who package up modules for Linux distributions

👍 

Same here. A license file would be helpful, so I submitted one in a PR.

**Comment by Bosch-Eli-Black** [comment]
Would love to see this happen :)

**Comment by char0n** [comment]
Yes this code is at this moment proprietary. ISC requires to have a full license text associated with the code.

**Comment by honzajavorek** [comment]
Closed by b5c58f7086b55e0cb3311de5cfcbefdc7d3fb295
